api = "0.12"

[builder]
id = "forgeon.builder.bun"
name = "Forgeon Bun Builder (Jammy)"
version = "0.1.0"

[stack]
id = "io.buildpacks.stacks.jammy"
build-image = "paketobuildpacks/build-jammy-base"
run-image   = "paketobuildpacks/run-jammy-base"

[[buildpacks]]
id = "forgeon/buildpack-bun"
uri = "docker://forgeon/buildpack-bun:0.1.0"

# If you have more:
# [[buildpacks]]
# id = "forgeon/buildpack-bun-deps"
# uri = "docker://forgeon/buildpack-bun-deps:0.1.0"
#
# [[buildpacks]]
# id = "forgeon/buildpack-bun-scripts"
# uri = "docker://forgeon/buildpack-bun-scripts:0.1.0"

[[order]]
  [[order.group]]
    id = "forgeon/buildpack-bun"
    version = "0.1.0"

  # then bun-deps, bun-scripts if you use them (same group)
  # [[order.group]]
  #   id = "forgeon/buildpack-bun-deps"
  #   version = "0.1.0"
  #
  # [[order.group]]
  #   id = "forgeon/buildpack-bun-scripts"
  #   version = "0.1.0"
