# builder.toml
description = "Forgeon Bun builder (Jammy)"

# IMPORTANT: buildpacks here must be OCI images
[[buildpacks]]
id = "forgeon/buildpack-bun"
version = "0.0.1"
uri = "localhost:5050/forgeon/buildpack-bun:0.0.1"

[[order]]
  [[order.group]]
  id = "forgeon/buildpack-bun"
  version = "0.0.1"

[build]
image = "paketobuildpacks/build-jammy-base:latest"

[run]
  [[run.images]]
  image = "paketobuildpacks/run-jammy-base:latest"
